### POST User ###
POST http://localhost:8000/users
Content-Type: application/json

{
    "id": 1,
    "name": "juan",
    "email": "test@test.com",
    "age": 30,
    "active": true
}

### PUT User ###
PUT http://localhost:8000/users/1
Content-Type: application/json

{
    "id": 2,
    "name": "eduardo",
    "email": "etest@test.com",
    "age": 35,
    "active": false
}