PUT http://localhost:8000/items/2

{
    "item": {
        "name": "Item 2",
        "description": "This is item 2",
        "price": 20.0,
        "tax": 2.0
    },
    
    "user": {
        "username": "johndoe",
        "full_name": "John Doe"
    },

    "priority": 5
}

###

PUT http://localhost:8000/item/2

{
    "item": {
        "name": "Item 2",
        "description": "This is item 2",
        "price": 20.0,
        "tax": 2.0
    },
    
    "user": {
        "username": "johndoe",
        "full_name": "John Doe"
    },

    "priority": 5
}